---
- name: Create a slave
  hosts: localhost
  connection: local
  roles:
    - role: add-hosts
    - role: add-external-repositories
    - role: add-pip
    - role: add-user
    - role: add-podman
    - role: add-nvim
    - role: add-vscodium
    - role: add-moonlight
    - role: add-desktop-environment
  # post_tasks:
  #   - name: Reboot to apply system changes
  #     become: yes
  #     reboot:
  #       msg: System ready!
