---
# [DesktopEnvironment]
- name: Install `tasksel` cli
  become: yes
  apt:
    name: tasksel

- name: Install LXQT task
  become: yes
  apt:
    name: task-lxqt-desktop

- name: Install LXQT ( Desktop Environment )
  become: yes
  shell: tasksel install lxqt-desktop

- name: Create LXQT config directory
  file:
    name: ~/.config/lxqt
    state: directory

- name: Install Openbox QT menu
  become: yes
  apt:
    name: obconf-qt

- name: Set Openbox as the default window manager
  copy:
    dest: ~/.config/lxqt/session.conf
    content: |
      [General]
      __userfile__=true
      window_manager=openbox
#

# [Themes]
- name: Create .themes folder
  file:
    path: ~/.themes
    state: directory

- name: Put WhiteSur theme
  unarchive:
    src: ./files/lxqt/.themes/WhiteSur.tar.gz
    dest: ~/.themes

- name: Create LXQT initial config file for Openbox
  copy:
    src: /etc/xdg/openbox/lxqt-rc.xml
    dest: ~/.config/openbox
    remote_src: yes

- name: Set WhiteSur theme as default
  lineinfile:
    path: ~/.config/openbox/lxqt-rc.xml
    line: <name>WhiteSur</name>
    regexp: <name>
    firstmatch: yes

- name: Set window button positions
  lineinfile:
    path: ~/.config/openbox/lxqt-rc.xml
    line: <titleLayout>CIML</titleLayout>
    regexp: <titleLayout>

- name: Disable animations on icons such as minimize or maximize
  lineinfile:
    path: ~/.config/openbox/lxqt-rc.xml
    line: <animateIconify>no</animateIconify>
    regexp: <animateIconify>

- name: Disable virtual desktops
  lineinfile:
    path: ~/.config/openbox/lxqt-rc.xml
    line: <primaryMonitor>1</primaryMonitor>
    regexp: <primaryMonitor>
#

# [Icons]
- name: Create .icons folder
  file:
    path: ~/.icons
    state: directory

- name: Put WhiteSur icons
  unarchive:
    src: ./files/lxqt/.icons/WhiteSur.tar.gz
    dest: ~/.icons

- name: Set WhiteSur icons as default
  copy:
    dest: ~/.config/lxqt/lxqt.conf
    content: |
      [General]
      __userfile__=true
      icon_theme=WhiteSur
      theme=kvantum

- name: Set WhiteSur cursor as default
  copy:
    dest: ~/.config/lxqt/lxqt-config-appearance.conf
    content: |
      [General]
      __userfile__=true

      [Mouse]
      cursor_theme=WhiteSur
#

# [Wallpaper]
- name: Create .wallpapers folder
  file:
    path: ~/.wallpapers
    state: directory

- name: Put WhiteSur wallpapers
  unarchive:
    src: ./files/lxqt/.wallpapers/WhiteSur.tar.gz
    dest: ~/.wallpapers

- name: Create PCManFM config directory
  file:
    name: ~/.config/pcmanfm-qt/lxqt
    state: directory

- name: Create PCManFM initial config file
  copy:
    src: /usr/share/pcmanfm-qt/lxqt/settings.conf
    dest: ~/.config/pcmanfm-qt/lxqt/settings.conf
    remote_src: yes

- name: Set WhiteSur wallpaper as default
  lineinfile:
    path: ~/.config/pcmanfm-qt/lxqt/settings.conf
    line: "Wallpaper=/home/{{ ansible_user_id }}/.wallpapers/WhiteSur/Vector-Wave3.jpg"
    regexp: Wallpaper=

- name: Enable wallpaper and stretch
  lineinfile:
    path: ~/.config/pcmanfm-qt/lxqt/settings.conf
    line: WallpaperMode=stretch
    regexp: WallpaperMode
#

# [Panels]
- name: Set panel positions
  template:
    src: "./files/lxqt/panel.conf.j2"
    dest: ~/.config/lxqt/panel.conf
#

# [Shortcuts]
# Copied from https://pastebin.com/NBkccE7B .
- name: Set keyboard shortcuts for window snapping
  blockinfile:
    path: ~/.config/openbox/lxqt-rc.xml
    insertbefore: </keyboard>
    content: |
      <keybind key="A-a">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>100%</height>
          <x>0%</x>
          <y>0%</y>
        </action>
      </keybind>
      <keybind key="A-d">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>100%</height>
          <x>50%</x>
          <y>0%</y>
        </action>
      </keybind>
      <keybind key="A-x">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>100%</width>
          <height>50%</height>
          <x>0%</x>
          <y>50%</y>
        </action>
      </keybind>
      <keybind key="A-w">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>100%</width>
          <height>50%</height>
          <x>0%</x>
          <y>0%</y>
        </action>
      </keybind>
      <keybind key="A-q">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>50%</height>
          <x>0%</x>
          <y>0%</y>
        </action>
      </keybind>
      <keybind key="A-e">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>50%</height>
          <x>50%</x>
          <y>0%</y>
        </action>
      </keybind>
      <keybind key="A-z">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>50%</height>
          <x>0%</x>
          <y>50%</y>
        </action>
      </keybind>
      <keybind key="A-c">
        <action name="UnmaximizeFull"/>
        <action name="MoveResizeTo">
          <width>50%</width>
          <height>50%</height>
          <x>50%</x>
          <y>50%</y>
        </action>
      </keybind>
      <keybind key="A-s">
        <action name="Maximize"/>
      </keybind>
      <keybind key="A-S-s">
        <action name="Iconify"/>
      </keybind>
#
