---
# [Conflictive packages]
- name: Uninstall XFWM4
  become: yes
  apt:
    name: xfwm4
    state: absent
#

# [WindowManager]
- name: Install Openbox ( Window Manager )
  become: yes
  apt:
    name: openbox
#

# [Keyboard shortcuts for window snapping]
- name: Create Openbox config directory
  file:
    path: ~/.config/openbox
    state: directory

# [Shortcuts]
# Copied from https://pastebin.com/NBkccE7B .
- name: Set keyboard shortcuts for window snapping
  become: yes
  blockinfile:
    path: /etc/xdg/openbox/rc.xml
    insertbefore: </keyboard>
    content: |2
        <keybind key="A-a">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>100%</height>
            <x>0%</x>
            <y>0%</y>
          </action>
        </keybind>
        <keybind key="A-d">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>100%</height>
            <x>50%</x>
            <y>0%</y>
          </action>
        </keybind>
        <keybind key="A-x">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>100%</width>
            <height>50%</height>
            <x>0%</x>
            <y>50%</y>
          </action>
        </keybind>
        <keybind key="A-w">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>100%</width>
            <height>50%</height>
            <x>0%</x>
            <y>0%</y>
          </action>
        </keybind>
        <keybind key="A-q">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>50%</height>
            <x>0%</x>
            <y>0%</y>
          </action>
        </keybind>
        <keybind key="A-e">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>50%</height>
            <x>50%</x>
            <y>0%</y>
          </action>
        </keybind>
        <keybind key="A-z">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>50%</height>
            <x>0%</x>
            <y>50%</y>
          </action>
        </keybind>
        <keybind key="A-c">
          <action name="UnmaximizeFull"/>
          <action name="MoveResizeTo">
            <width>50%</width>
            <height>50%</height>
            <x>50%</x>
            <y>50%</y>
          </action>
        </keybind>
        <keybind key="A-s">
          <action name="Maximize"/>
        </keybind>
        <keybind key="A-S-s">
          <action name="Iconify"/>
        </keybind>
#
