---
# [Conflictive packages]
- name: Uninstall XFWM4
  become: yes
  apt:
    name: xfwm4
    state: absent
#

# [WindowManager]
- name: Install Openbox ( Window Manager )
  become: yes
  apt:
    name: openbox
#
