---
- name: Install Podman
  become: yes
  apt:
    name: podman

- name: Add registries
  copy:
    dest: /etc/containers/registries.conf
    content: |
      [registries.search]
      registries = ['docker.io']

      [registries.insecure]
      registries = []

      [registries.block]
      registries = []

# Use v<1.0 because Debian11 uses podman 3.0.1 and
# podman-compose requires podman 3.1 as a minimum.
# TODO: Change for apt when they release a stable version.
- name: Add podman-compose
  pip:
    name: podman-compose<1.0

- name: Install dbus-user-session to run podman in rootless mode
  become: yes
  apt:
    name: dbus-user-session

- name: Start dbus service
  systemd:
    name: dbus
    state: started
    scope: user
    enabled: true
