---
# Steps extracted from https://github.com/nodesource/distributions .

- name: Install dependencies to add Nodesource repository
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Import Nodesource GPG key
  become: yes
  shell: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

- name: Create deb repository with NodeJS v18.x
  become: yes
  shell: echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

- name: Install NodeJS
  become: yes
  apt:
    name: nodejs
    update_cache: yes # Runs an `apt update` before the install.
